#!/usr/bin/env python3
"""
generate_seed_sql.py
─────────────────────────────────────────────────────────────
One-time script: reads the content extracted directly from the
original index.html (final_master_content.json) and generates
014_seed_template_tenant_data.sql — a SQL script that:

  1. Creates the reserved "template tenant" row (is_template = true)
  2. Populates every content table for that tenant with the REAL
     default content (99 Allah names, 97 Prophet names as found in
     source, 40 hadiths, 35 masnoon duas, 6 kalimas, pillars,
     prayers, Q&A, contact info, about page, books, home menu).

No placeholder/invented content is generated — every value here
traces back to a literal string found in the attached index.html.

Run once with:
    python3 generate_seed_sql.py > ../migrations/014_seed_template_tenant_data.sql
Then apply with:
    psql "$DATABASE_URL" -f 014_seed_template_tenant_data.sql
─────────────────────────────────────────────────────────────
"""
import json
import sys

with open('/home/user/schema/final_master_content.json', encoding='utf-8') as f:
    D = json.load(f)

TEMPLATE_TENANT_ID = "00000000-0000-0000-0000-000000000001"

def esc(s):
    """SQL string literal escaping. None -> NULL."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

def esc_arr(arr):
    if not arr:
        return "'{}'"
    escaped = [str(x).replace("'", "''").replace(",", "\\,") for x in arr]
    inner = ",".join(escaped)
    return "'{" + inner + "}'"

out = []
w = out.append

w("-- ═══════════════════════════════════════════════════════════")
w("-- 014_seed_template_tenant_data.sql")
w("-- AUTO-GENERATED by seed/generate_seed_sql.py — DO NOT HAND-EDIT.")
w("-- Regenerate from final_master_content.json if source content changes.")
w("--")
w("-- Populates the reserved TEMPLATE TENANT with the real default")
w("-- content extracted from the original single-tenant index.html.")
w("-- This is the 'gold master' every new tenant is seeded from via")
w("-- seed_tenant_defaults().")
w("-- ═══════════════════════════════════════════════════════════")
w("")
w("do $$")
w("declare")
w(f"  v_tenant_id uuid := '{TEMPLATE_TENANT_ID}';")
w("  v_edition16_id uuid;")
w("  v_edition15_id uuid;")
w("  v_cat_id uuid;")
w("  v_collection_id uuid;")
w("  v_pillar_id uuid;")
w("  v_guide_id uuid;")
w("begin")
w("")

# ── Tenant + branding ──
w("  -- ── Template tenant ─────────────────────────────")
w(f"  insert into tenants (id, slug, name, status, is_template, timezone, default_language)")
w(f"    values (v_tenant_id, 'template', 'Islamic Coaching Institute (Template)', 'active', true, 'Asia/Karachi', 'en')")
w(f"    on conflict (id) do nothing;")
w("")
w("  insert into tenant_branding (tenant_id, app_name, short_name, tagline, description, theme_color, background_color, primary_color_hex, secondary_color_hex, sw_cache_version)")
w(f"    values (v_tenant_id, 'Islamic Coaching Institute', 'ICI', {esc('Guiding Hearts • Illuminating Minds')}, {esc('Learn Islam — Anywhere, Anytime')}, '#0284C7', '#FFFFFF', '#0284C7', '#0EA5E9', '1')")
w("    on conflict (tenant_id) do nothing;")
w("")

# ── Quran editions + paras ──
para_names = D["paraNames"]
para_ids16 = D["paraFileIds16"]
w("  -- ── Quran Editions & Paras ───────────────────────")
w("  insert into quran_editions (tenant_id, name, line_count, sort_order, is_active)")
w(f"    values (v_tenant_id, '16 Line Quran', 16, 1, true) returning id into v_edition16_id;")
w("  insert into quran_editions (tenant_id, name, line_count, sort_order, is_active)")
w(f"    values (v_tenant_id, '15 Line Quran', 15, 2, true) returning id into v_edition15_id;")
w("")
for i, (name, fid) in enumerate(zip(para_names, para_ids16), start=1):
    w(f"  insert into quran_paras (tenant_id, edition_id, para_number, name_arabic, file_provider, file_reference, sort_order)")
    w(f"    values (v_tenant_id, v_edition16_id, {i}, {esc(name)}, 'google_drive', {esc(fid)}, {i});")
w("")
# 15-line edition: same para names/numbers, but source app has NO file id wiring for it
# (card.onclick was never attached in the original code) -> file_reference NULL, file_provider 'none'
for i, name in enumerate(para_names, start=1):
    w(f"  insert into quran_paras (tenant_id, edition_id, para_number, name_arabic, file_provider, file_reference, sort_order)")
    w(f"    values (v_tenant_id, v_edition15_id, {i}, {esc(name)}, 'none', NULL, {i});")
w("")

# ── Qaida courses ──
w("  -- ── Qaida Courses ────────────────────────────────")
w("  insert into qaida_courses (tenant_id, name, level_label, color_theme, file_provider, file_reference, sort_order, is_active)")
w(f"    values (v_tenant_id, 'Noorani Qaida', 'Beginner', 'sky', 'google_drive', {esc('1iMJxrguPIsAUqViR_JsMr_BS0LrhCSPX')}, 1, true);")
w("  insert into qaida_courses (tenant_id, name, level_label, color_theme, file_provider, file_reference, sort_order, is_active)")
w("    values (v_tenant_id, 'Qurani Qaida', 'Intermediate', 'green', 'none', NULL, 2, true);")
w("")

# ── Divine names ──
w("  -- ── Allah's 99 Names ─────────────────────────────")
for i, n in enumerate(D["allahNames"], start=1):
    w(f"  insert into divine_names (tenant_id, category, order_index, arabic, transliteration, meaning_en, meaning_urdu)")
    w(f"    values (v_tenant_id, 'allah', {i}, {esc(n['ar'])}, {esc(n['en'])}, {esc(n['meaning'])}, {esc(n['ur'])});")
w("")
w("  -- ── Prophet's Names (97 present in source; UI label says 99 — see delivery notes) ──")
for i, n in enumerate(D["prophetNames"], start=1):
    w(f"  insert into divine_names (tenant_id, category, order_index, arabic, transliteration, meaning_en, meaning_urdu)")
    w(f"    values (v_tenant_id, 'prophet', {i}, {esc(n['ar'])}, {esc(n['en'])}, {esc(n['meaning'])}, {esc(n['ur'])});")
w("")

# ── Dua categories + duas ──
w("  -- ── Dua Categories & Duas ────────────────────────")
w("  insert into dua_categories (tenant_id, slug, title, subtitle, icon, display_type, sort_order)")
w(f"    values (v_tenant_id, 'masnoon', 'Daily Masnoon Duas', 'Morning & Evening Supplications', 'stars', 'list_screen', 1) returning id into v_cat_id;")
for i, dua in enumerate(D["masnoonDuas"], start=1):
    w(f"  insert into duas (tenant_id, category_id, title, subtitle, arabic_text, translation_en, icon, sort_order)")
    w(f"    values (v_tenant_id, v_cat_id, {esc(dua['title'])}, {esc(dua['subtitle'])}, {esc(dua['arabic'])}, {esc(dua['translation'])}, {esc(dua['icon'])}, {i});")
w("")

w("  insert into dua_categories (tenant_id, slug, title, subtitle, icon, display_type, sort_order)")
w("    values (v_tenant_id, 'kalimas', '6 Kalimas', 'Foundations of Faith', 'format_list_numbered', 'modal', 2) returning id into v_cat_id;")
for k in D["duaModals"]["kalimas"]:
    w(f"  insert into duas (tenant_id, category_id, title, arabic_text, translation_en, numbered_position, sort_order)")
    w(f"    values (v_tenant_id, v_cat_id, {esc(k['title'])}, {esc(k['arabic'])}, {esc(k['translation'])}, {k['number']}, {k['number']});")
w("")

single = D["duaModals"]["single_modals"]
single_meta = [
    ("ayat_kursi", "Ayat-ul-Kursi", "The Throne Verse", "star_outline"),
    ("dua_qunoot", "Dua-e-Qunoot", "Recited in Witr prayers", "volunteer_activism"),
    ("iman_mujmal", "Iman-e-Mujmal", "Core belief statement", "radio_button_checked"),
    ("iman_mufassal", "Iman-e-Mufassal", "Core belief statement", "radio_button_checked"),
]
for idx, (key, title, subtitle, icon) in enumerate(single_meta, start=3):
    m = single[key]
    w(f"  insert into dua_categories (tenant_id, slug, title, subtitle, icon, display_type, sort_order)")
    w(f"    values (v_tenant_id, {esc(key)}, {esc(title)}, {esc(subtitle)}, {esc(icon)}, 'modal', {idx}) returning id into v_cat_id;")
    w(f"  insert into duas (tenant_id, category_id, title, arabic_text, translation_en, sort_order)")
    w(f"    values (v_tenant_id, v_cat_id, {esc(title)}, {esc(m['arabic'])}, {esc(m['translation'])}, 1);")
    w("")

# ── Hadith ──
w("  -- ── 40 Hadiths ───────────────────────────────────")
w("  insert into hadith_collections (tenant_id, name, sort_order)")
w("    values (v_tenant_id, '40 Hadiths', 1) returning id into v_collection_id;")
for i, text in enumerate(D["hadithList"], start=1):
    w(f"  insert into hadiths (tenant_id, collection_id, hadith_number, text_en, sort_order)")
    w(f"    values (v_tenant_id, v_collection_id, {i}, {esc(text)}, {i});")
w("")

# ── Books ──
w("  -- ── Islamic Books ────────────────────────────────")
gradients = {
    "Riyadh as-Salihin": "linear-gradient(135deg,#006591,#0ea5e9)",
    "Sahih Bukhari": "linear-gradient(135deg,#059669,#10b981)",
    "Ar-Raheeq Al-Makhtum": "linear-gradient(135deg,#7c3aed,#a855f7)",
}
cat_map = {"Hadith": "hadith", "Seerah": "seerah"}
for i, b in enumerate(D["books"], start=1):
    category = "other"
    for tag in b["tags"]:
        if tag in cat_map:
            category = cat_map[tag]
    lang_tags = [t for t in b["tags"] if t not in cat_map]
    grad = gradients.get(b["title"], "linear-gradient(135deg,#006591,#0ea5e9)")
    w(f"  insert into books (tenant_id, title, author, category, language_tags, cover_icon, cover_gradient, file_provider, sort_order, is_active)")
    w(f"    values (v_tenant_id, {esc(b['title'])}, {esc(b['author'])}, {esc(category)}, {esc_arr(lang_tags)}, 'auto_stories', {esc(grad)}, 'none', {i}, true);")
w("")

# ── Pillars ──
w("  -- ── 5 Pillars of Islam ───────────────────────────")
pillar_order = ["shahada", "salah", "zakat", "sawm", "hajj"]
for i, slug in enumerate(pillar_order, start=1):
    p = D["pillarData"][slug]
    w(f"  insert into pillars (tenant_id, slug, title, arabic_text, description, importance, sort_order)")
    w(f"    values (v_tenant_id, {esc(slug)}, {esc(p['title'])}, {esc(p['arabic'])}, {esc(p['description'])}, {esc(p['importance'])}, {i}) returning id into v_pillar_id;")
    for j, d in enumerate(p["details"], start=1):
        w(f"  insert into pillar_details (tenant_id, pillar_id, detail_text, sort_order)")
        w(f"    values (v_tenant_id, v_pillar_id, {esc(d)}, {j});")
    for j, g in enumerate(p["guide"], start=1):
        w(f"  insert into pillar_guide_steps (tenant_id, pillar_id, title, description, sort_order)")
        w(f"    values (v_tenant_id, v_pillar_id, {esc(g['title'])}, {esc(g['desc'])}, {j});")
    w("")

# ── Prayers ──
w("  -- ── Prayers (rakat info) ─────────────────────────")
def parse_rakat_breakdown(rakat_text):
    """'4 Sunnah, 4 Fard, 2 Sunnah, 2 Nafl' -> ordered JSON list + summary totals."""
    parts = [p.strip() for p in rakat_text.split(",")]
    breakdown = []
    totals = {"Fard": 0, "Sunnah": 0, "Nafl": 0, "Witr": 0}
    for p in parts:
        count_str, type_str = p.split(" ", 1)
        count = int(count_str)
        breakdown.append({"type": type_str, "count": count})
        if type_str in totals:
            totals[type_str] += count
    return breakdown, totals

for i, pr in enumerate(D["prayersData"]["prayers"], start=1):
    breakdown, totals = parse_rakat_breakdown(pr["rakat_text"])
    breakdown_json = json.dumps(breakdown).replace("'", "''")
    w(f"  insert into prayers (tenant_id, name, time_label, rakat_fard, rakat_sunnah, rakat_nafl, rakat_witr, rakat_breakdown, sort_order)")
    w(f"    values (v_tenant_id, {esc(pr['name'])}, {esc(pr['time_label'])}, {totals['Fard']}, {totals['Sunnah']}, {totals['Nafl']}, {totals['Witr']}, '{breakdown_json}'::jsonb, {i});")
w("")

# ── Ritual guides: Wudu, Namaz Lesson, How to Perform ──
w("  -- ── Ritual Guides: Wudu ──────────────────────────")
w("  insert into ritual_guides (tenant_id, guide_type, title, intro_text, sort_order)")
w(f"    values (v_tenant_id, 'wudu', 'Wudu (Ablution)', {esc('Step-by-step purification guide.')}, 1) returning id into v_guide_id;")
for i, step in enumerate(D["wuduSteps"], start=1):
    w(f"  insert into ritual_guide_steps (tenant_id, guide_id, step_number, title, description, icon, sort_order)")
    w(f"    values (v_tenant_id, v_guide_id, {i}, {esc(step['title'])}, {esc(step['desc'])}, {esc(step['icon'])}, {i});")
w("")

w("  -- ── Ritual Guides: Namaz Lesson ──────────────────")
w("  insert into ritual_guides (tenant_id, guide_type, title, sort_order)")
w("    values (v_tenant_id, 'namaz_lesson', 'Namaz Lesson', 2) returning id into v_guide_id;")
for i, lesson in enumerate(D["prayersData"]["namaz_lessons"], start=1):
    w(f"  insert into ritual_guide_steps (tenant_id, guide_id, step_number, title, description, arabic_text, sort_order)")
    w(f"    values (v_tenant_id, v_guide_id, {i}, {esc(lesson['title'])}, {esc(lesson['translation'])}, {esc(lesson['arabic'])}, {i});")
w("")

w("  -- ── Ritual Guides: How to Perform Namaz ──────────")
w("  insert into ritual_guides (tenant_id, guide_type, title, sort_order)")
w("    values (v_tenant_id, 'namaz_how_to', 'How to Perform', 3) returning id into v_guide_id;")
for step in D["prayersData"]["how_to_perform"]:
    w(f"  insert into ritual_guide_steps (tenant_id, guide_id, step_number, title, description, sort_order)")
    w(f"    values (v_tenant_id, v_guide_id, {step['step']}, {esc(step['title'])}, {esc(step['desc'])}, {step['step']});")
w("")

# ── Q&A ──
w("  -- ── Islamic Q&A ──────────────────────────────────")
for i, qa in enumerate(D["qaData"], start=1):
    w(f"  insert into qa_items (tenant_id, category, question, answer, sort_order, is_active)")
    w(f"    values (v_tenant_id, {esc(qa['cat'])}, {esc(qa['q'])}, {esc(qa['a'])}, {i}, true);")
w("")

# ── Site pages: About + Home hero ──
about = D["about"]
about_blocks = []
for p in about["about_paragraphs"]:
    about_blocks.append({"type": "paragraph", "text": p})
about_blocks.append({"type": "tags", "items": about["about_tags"]})
about_blocks.append({"type": "offerings", "items": about["offerings"]})
about_blocks.append({"type": "developer", "name": about["developer_name"], "org": about["developer_org"]})
about_blocks.append({"type": "footer_note", "text": about["footer_note"]})
about_blocks.append({"type": "copyright", "text": about["copyright"]})
about_blocks_json = json.dumps(about_blocks, ensure_ascii=False).replace("'", "''")

w("  -- ── Site Pages: About ────────────────────────────")
w(f"  insert into site_pages (tenant_id, page_key, hero_title, hero_subtitle, content_blocks)")
w(f"    values (v_tenant_id, 'about', {esc(' '.join(about['hero_title_lines']))}, {esc(about['hero_tagline'])}, '{about_blocks_json}'::jsonb);")
w("")

home_hero_blocks = json.dumps([{"type": "version", "text": about["version"]}], ensure_ascii=False).replace("'", "''")
w("  -- ── Site Pages: Home Hero ────────────────────────")
w(f"  insert into site_pages (tenant_id, page_key, hero_title, hero_subtitle, content_blocks)")
w(f"    values (v_tenant_id, 'home_hero', 'Islamic Coaching Institute', {esc('Learn Islam — Anywhere, Anytime')}, '{home_hero_blocks}'::jsonb);")
w("")

# ── Contact channels ──
contact = D["contact"]
w("  -- ── Contact Channels ─────────────────────────────")
w(f"  insert into contact_channels (tenant_id, channel_type, label, value, icon, sort_order) values")
w(f"    (v_tenant_id, 'phone', 'Phone', {esc(contact['phone']['label'])}, 'call', 1),")
w(f"    (v_tenant_id, 'whatsapp', 'WhatsApp', {esc(contact['whatsapp']['label'])}, 'chat', 2),")
w(f"    (v_tenant_id, 'email', 'Email', {esc(contact['email']['label'])}, 'mail', 3),")
w(f"    (v_tenant_id, 'address', 'Address', {esc(contact['address'])}, 'location_on', 4),")
w(f"    (v_tenant_id, 'social', 'Facebook', {esc(contact['facebook']['label'])}, 'group', 5),")
w(f"    (v_tenant_id, 'social', 'YouTube', {esc(contact['youtube']['label'])}, 'play_circle', 6),")
w(f"    (v_tenant_id, 'social', 'Instagram', {esc(contact['instagram']['label'])}, 'photo_camera', 7);")
w("")
for i, wh in enumerate(contact["working_hours"], start=8):
    w(f"  insert into contact_channels (tenant_id, channel_type, label, value, icon, sort_order)")
    w(f"    values (v_tenant_id, 'working_hours', {esc(wh['label'])}, {esc(wh['value'])}, 'schedule', {i});")
w("")

# ── Home menu items ──
w("  -- ── Home Menu Items (dashboard cards) ────────────")
menu_items = [
    ("quran_16line", "reading", "16 Line Quran", True, 1),
    ("quran_15line", "reading", "15 Line Quran", True, 2),
    ("qaida", "reading", "Read Qaida", True, 3),
    ("daily_duas", "reading", "Daily Duas", True, 4),
    ("allah_names", "reading", "Allah Names", True, 5),
    ("prophet_names", "reading", "Prophet Names", True, 6),
    ("hadith", "reading", "40 Hadiths", True, 7),
    ("pillars", "learning", "Pillars of Islam", True, 1),
    ("islamic_knowledge", "learning", "Islamic Knowledge", False, 2),
    ("prayers", "learning", "Prayers", True, 3),
    ("books", "learning", "Islamic Books", True, 4),
]
for key, section, label, enabled, order in menu_items:
    w(f"  insert into home_menu_items (tenant_id, module_key, section, custom_label, is_enabled, sort_order)")
    w(f"    values (v_tenant_id, {esc(key)}, {esc(section)}, {esc(label)}, {str(enabled).lower()}, {order});")
w("")

w("end $$;")
w("")

print("\n".join(out))
